services:
  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - trajectory-storage-network

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    stdin_open: true
    ports:
      - 8000:8000
    networks:
      - trajectory-storage-network

networks:
  trajectory-storage-network:
    driver: bridge
