INITIAL_PARTICLES_AMOUNT: int = 2000

PEDESTRIAN_SIZE: int = 15

SEARCH_NEAREST_INSIDE_RANGE: int = 300

CONVERGENCE_DECENTRALIZATION_THRESHOLD: float = 1.0

CLUSTER_AMOUNT_THRESHOLD: int = 2

CONVERGENCE_JUDGEMENT_NUMBER: int = 30

MISSING_PARTICLE_THRESHOLD: int = int(INITIAL_PARTICLES_AMOUNT / 2)

CONFISCATE_PARTICLES_AMOUNT: int = int(INITIAL_PARTICLES_AMOUNT / 5)

STEP: int = 60

X_MEANS_CLUSTER_AMOUNT: int = 3
